<section id="login-block">
    <div class="block-border">
	<div class="block-content">

	    <h1>Admin</h1>

	    <div class="block-header">Acesso Restrito</div>

	    <form class="form with-margin" name="login-form" id="login-form" method="post" action="<?php echo $this->path( 'login' ); ?>">
		<input type="hidden" name="a" id="a" value="send">

		<p class="inline-small-label">
		    <label for="login"><span class="big">E-mail:</span></label>
		    <input type="text" name="email" id="email" class="full-width" value="">
		</p>

		<p class="inline-small-label">
		    <label for="pass"><span class="big">Senha:</span></label>
		    <input type="password" name="senha" id="senha" class="full-width" value="">
		</p>

		<button type="submit" class="float-right">Entrar</button>

		<p class="input-height">
		    <input type="checkbox" name="keep-logged" id="keep-logged" value="1" class="mini-switch" checked="checked">
		    <label for="keep-logged" class="inline">Manter-me logado</label>
		</p>
	    </form>

	    <form class="form" id="password-recovery" method="post" action="<?php echo $this->path( 'password' ); ?>">
		<fieldset class="grey-bg no-margin collapse">
		    <legend><a href="javascript:;">Esqueceu sua senha?</a></legend>

		    <p class="input-with-button">
			<label for="recovery-mail">Infome seu endere&ccedil;o de e-mail</label>

			<span class="relative">
			    <input type="text" name="recovery-mail" class="full-width" id="recovery-mail" value="">
			</span>

			<button type="submit" class="float-right">Enviar</button>
		    </p>
		</fieldset>
	    </form>
	</div></div>
</section>
