<table id="arquivo-grid" width="100%" cellspacing="0" class="table sortable no-margin">
    <thead>
	<tr>
	    <th class="black-cell sorting_disabled" style="width: 17px;"><span></span></th>
	    <th scope="col" style="width: 330px;" class="sorting">
		<span class="column-sort">
		    <a class="sort-up" title="Sort up" href="#"></a>
		    <a class="sort-down" title="Sort down" href="#"></a>
		</span>
		Arquivo
	    </th>
	    <th scope="col" style="width: 250px;" class="sorting">
		<span class="column-sort">
		    <a class="sort-up" title="Sort up" href="#"></a>
		    <a class="sort-down" title="Sort down" href="#"></a>
		</span>
		Usu&aacute;rio
	    </th>
	    <th scope="col" style="width: 120px;" class="sorting">
		<span class="column-sort">
		    <a class="sort-up" title="Sort up" href="#"></a>
		    <a class="sort-down" title="Sort down" href="#"></a>
		</span>
		Extens&atilde;o
	    </th>
	    <th scope="col" style="width: 150px;" class="sorting">
		<span class="column-sort">
		    <a class="sort-up" title="Sort up" href="#"></a>
		    <a class="sort-down" title="Sort down" href="#"></a>
		</span>
		A&ccedil;&atilde;o
	    </th>
	    <th scope="col" style="width: 150px;" class="sorting">
		<span class="column-sort">
		    <a class="sort-up" title="Sort up" href="#"></a>
		    <a class="sort-down" title="Sort down" href="#"></a>
		</span>
		Data / Hora
	    </th>
	</tr>
    </thead>

    <tbody>
	<?php foreach ( $this->rows as $key => $value ): ?>
    	<tr class="<?php echo $this->cycle( array('odd', 'even') )->next(); ?>">
	    <td class="th table-check-cell sorting_1"><?php echo ++$key; ?></td>
    	    <td><?php echo $value->arquivo; ?></td>
    	    <td><?php echo $value->nome; ?></td>
    	    <td><?php echo $value->extensao; ?></td>
    	    <td><?php echo $this->geral()->detalhaAcaoLog( $value->acao ); ?></td>
    	    <td><?php echo $this->date( $value->data, 'dd/MM/yyyy HH:m:ss' ); ?></td>
    	</tr>
	<?php endforeach; ?>
    </tbody>
</table>