<?php $this->headScript()->appendFile( $this->baseUrl('public/scripts/js/includes/graficos.js') ); ?>

<div class="block-border">
    <div class="block-content">
        <h1>Gr&aacute;ficos</h1>
             
        <div class="block-controls">
            <ul class="controls-tabs js-tabs with-children-tip">
		 <li class="current">
		    <a href="#graph-acoes" title="A&ccedil;&otilde;es" onClick="initGraficoAcoes();">
			<img src="<?php echo $this->baseUrl('public/images/icons/web-app/24/Picture.png'); ?>" width="24" height="24" />
		    </a>
		</li>
                <li>
		    <a href="#graph-extensoes" title="Extens&otilde;es" onClick="initGraficoExtensoes();">
			<img src="<?php echo $this->baseUrl('public/images/icons/web-app/24/Pie-Chart.png'); ?>" width="24" height="24" />
		    </a>
		</li>
                <li>
		    <a href="#graph-categorias" title="Categorias" onClick="initGraficoCategorias();">
			<img src="<?php echo $this->baseUrl('public/images/icons/web-app/24/Comment.png'); ?>" width="24" height="24" />
		    </a>
		</li>
                <li>
		    <a href="#graph-perfil" title="Perfil" onClick="initGraficoPerfil();">
			<img src="<?php echo $this->baseUrl('public/images/icons/web-app/24/Profile.png'); ?>" width="24" height="24" />
		    </a>
		</li>
		<li>
		    <a href="#graph-baixados" title="Mais baixados" onClick="initGraficoBaixados();">
			<img src="<?php echo $this->baseUrl('public/images/icons/web-app/24/Bar-Chart.png'); ?>" width="24" height="24" />
		    </a>
		</li>
            </ul>
        </div>
         
	<div id="graph-acoes">
	    <div id="container-graph-acoes" class="graficos"></div>
	</div>
        <div id="graph-extensoes">
	    <div id="container-graph-extensoes" class="graficos"></div>
	</div>
        <div id="graph-categorias">
	    <div id="container-graph-categorias" class="graficos"></div>
	</div>
        <div id="graph-perfil">
	    <div id="container-graph-perfil" class="graficos"></div>
	</div>
	<div id="graph-baixados">
	    <div id="container-graph-baixados" class="graficos"></div>
	</div>
    </div>
</div>