<div style="border: 1px solid #B5C6CF; background-color: #D1E4EF; padding: 3px; font-family: verdana, arial; font-size: 12px; color: #666;">
    <div style="background-color: #FFF">
        <h1 style="border-bottom: 4px solid #B5C6CF; margin:0; padding: 23px; font-weight: normal; min-height: 30px; color: #5790AF;">
	    Altera&ccedil;&atilde;o de senha - <?php echo $this->config->geral->title; ?>
	</h1>
        <div style="margin:0px 1px 1px 1px; background-color: #EFF9FF; ">
            <div id="corpo" style="padding: 5px 10px; margin: 0; width: 90%;">
                <p>
                    Prezado Usu&aacute;rio,<br/>
                    Foi solicitada uma nova senha ao sistema.
                </p>
                <p style="padding:5px; border: 1px dotted #CCC;">
                    Se voc&ecirc; esqueceu sua senha e deseja receber uma nova, 
		    <a href="<?php echo $this->link; ?>"><b>clique aqui</b><br/></a>
                </p>
            </div>
        </div>

    </div>   
</div>
<p style="font-family: verdana, arial; font-size: 11px; text-align: center;">Mensagem autom&aacute;tica, por favor n&atilde;o responda esse email.</p>