<fieldset class="grey-bg">

    <ul class="tabs js-tabs same-height">
	<li class="current"><a href="#tab-listagem">Listagem</a></li>
	<li><a href="#tab-cadastro">Cadastro</a></li>
    </ul>

    <div class="tabs-content" id="tab-tags">

	<div id="tab-listagem" class="tabs">

	    <p class="input-type-text form">
		<input type="text" name="simple-search" id="simple-search" style="width: 90%" title="Filtra tags" />
		<img width="16" height="16" src="<?php echo $this->baseUrl( 'public/images/icons/fugue/magnifier.png' ); ?>" class="float-right" />
	    </p>

	    <p>
		<ul id="list-tags" style="height: 178px; overflow: auto;" class="simple-list with-icon">
		    <?php
			if ( !empty( $this->tags ) ) :
			    foreach ( $this->tags as $tag ) :
		    ?>
			<li>
			    <a href="javascript:;">
				<input value='<?php echo json_encode( $tag->toArray() ); ?>' 
				       type="checkbox" style="display: none" class="tag_sel" />
				<p class="label-tags"><?php echo $tag->titulo; ?></p>
			    </a>
			</li>
		    <?php
			    endforeach;
			endif;
		    ?>
		</ul>
	    </p>
	    
	    <div style="text-align: center">
		<button class="small" onClick="addTags();">
		    <img width="16" height="16" src="<?php echo $this->baseUrl( 'public/images/icons/fugue/plus-circle.png' ); ?>">
		    Adicionar
		</button>
		<button class="small" onClick="checkAllTags();">
		    <img width="16" height="16" src="<?php echo $this->baseUrl( 'public/images/icons/fugue/pin-small.png' ); ?>">
		    Marcar Todos
		</button>
	    </div>
	    
	</div>

	<div id="tab-cadastro" class="tabs">
	    <form method="<?php echo $this->form->getMethod() ?>" 
		  class="form" 
		  action="<?php echo $this->form->getAction() ?>" 
		  onsubmit="return saveTag(this);">
		    <fieldset class="grey-bg">
			    <?php echo $this->form->getElement('id'); ?>

			    <p>
				<span class="relative">
					<label for="titulo" class="required">T&iacute;tulo:</label>
					<?php echo $this->form->getElement('titulo'); ?>
				</span>
			    </p>

			    <div style="text-align: center">
				<button type="submit">
				    <img width="16" height="16" src="<?php echo $this->baseUrl( 'public/images/icons/fugue/disk.png' ); ?>">
				    Salvar
				</button>
			    </div>
		    </fieldset>
	    </form>  
	</div>
    </div>

</fieldset>